OPTIONS(ERRORS=0)
LOAD DATA
CHARACTERSET JA16SJIS
INFILE 'ADDRESS_MASTER.dat'
TRUNCATE
INTO TABLE MM住所コード情報
FIELDS TERMINATED BY ','
(
連番          SEQUENCE(MAX),
郵便番号,
住所１,
住所２,
データ抽出日 CHAR "TO_NUMBER(TO_CHAR(TO_DATE(:データ抽出日, 'YYYY/MM/DD HH24:MI:SS'), 'YYYYMMDD'))"
)
