OPTIONS (ERRORS = 0)
LOAD DATA
CHARACTERSET JA16SJIS
INFILE 'NG_PROMOTION_MEMBER_LIST_ORG.CSV'
TRUNCATE
INTO TABLE WSポイント付与会員O
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"'
(
     発注番号
    ,カード番号    "REPLACE(:カード番号,'-','')"
)
