OPTIONS (ERRORS = 0)
LOAD DATA
CHARACTERSET JA16SJIS
INFILE 'NG_PROMOTION_AMOUNT_POINT_ORG.CSV'
TRUNCATE
INTO TABLE WSポイント付与買上高O
FIELDS TERMINATED BY '\t' OPTIONALLY ENCLOSED BY '"'
(
     発注番号
    ,枝番
    ,適用下限額
    ,計算基準単位額
    ,倍率固定ポイント値
)