OPTIONS(ERRORS=0)
LOAD DATA
CHARACTERSET JA16SJIS
INFILE '%INPUTFILE%'
APPEND
INTO TABLE %TABLE%
FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"'
(
     クーポンＩＤ
    ,ＯＣＰＦユーザＩＤ
    ,クーポン配信日時   CHAR "TO_DATE(:クーポン配信日時, 'YYYY/MM/DD HH24:MI:SS')"
)

